main:
  - name: Syllabus
    url: /syllabus/
    weight: 1
  - name: Schedule
    url: /schedule/
    weight: 2
  - name: Classes
    url: /weeks/
    weight: 3
  - name: Resources
    url: /resources/
    weight: 4
