main:
  - name: Syllabus
    url: /syllabus/
    weight: 1
  - name: Schedule
    url: /schedule/
    weight: 2
  - name: Classes
    url: /weeks/
    weight: 3
  - name: CampusWire
    url: https://campuswire.com/p/GF9F6AD11
    weight: 4
  - name: Resources
    url: /course-resources/
    weight: 5
  - name: Downloads
    url: /downloads/
    weight: 6
  - name: Blackboard
    url: https://elearning.villanova.edu
    weight: 7
